Prevent installing on windows
`set.cfg` has a classifier indicating `POSIX` but that is not enforced
by `pip`, so `pip install dtrx` succeeds, but running `dtrx` will fail
due to missing `fcntl` module.

Add a hacky way to prevent installing on windows, by specifying a
non-existent dependency on that platform:

```config
install_requires =
    platform==unsupported;platform_system=="Windows"
```

This causes install to fail with:

```plaintext
ERROR: Could not find a version that satisfies the requirement platform==unsuppo
rted; platform_system == "Windows" (from dtrx) (from versions: none)
ERROR: No matching distribution found for platform==unsupported; platform_system
```

Add a test to verify this behavior.

Bump version to 8.3.1 for releasing this fix.

Fixes #30.